spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
